### ISSUE TITLE
Failing tests: testGiveEOA() and testTakeEOA() 

### ISSUE THREAD

**Issue by ra-phael** [attestate/ERC4973#46]
I was running the tests and noticed that `testTakeEOA` and `testGiveEOA` are failing with
```
[FAIL. Reason: _safeCheckAgreement: invalid signature]
```

It seems that it's because v is missing here: 
https://github.com/rugpullindex/ERC4973/blob/1c8d612d78739c2f7bd8cae95be808bcbf3a1cae/src/ERC4973.t.sol#L406

I commented out the parts where the signature is checked against the hardcoded one and all the tests are passing.

**Comment by TimDaub** [comment]
related: https://github.com/ethers-io/ethers.js/issues/3262

**Comment by TimDaub** [comment]
I think this isn't the case anymore with us fixing https://github.com/advisories/GHSA-4h98-2769-gh6h
